skip_tags: true

os: "Visual Studio 2019"

environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"

build_script:
  - "git --no-pager log -n2"
  - "echo %APPVEYOR_REPO_COMMIT%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;;%PATH%"
  - "python --version"
  - "pip install -r requirements/tests.txt"
  - "pip list"

test_script:
  - "python run_tests.py"
