repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: double-quote-string-fixer
      - id: check-toml
      - id: check-yaml

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        args: ["--uri-ignore-words-list", "*"]  # https://github.com/codespell-project/codespell/issues/2473

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.283
    hooks:
      - id: pyright

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: setup.py|docs/conf.py|tests

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.172
    hooks:
      - id: ruff

  - repo: https://github.com/dosisod/refurb
    rev: v1.8.0
    hooks:
      - id: refurb
