name: Lint
"on":
  push:
    branches:
      - main
      - dev
      - deps
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -U pip && pip install -U setuptools wheel
      - name: install dependencies
        run: pip install -r requirements/lint.txt
      - uses: pre-commit/action@v2.0.3
