name: Lint

"on":
  push:
    branches:
      - main
      - dev
      - deps
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip setuptools wheel
      - name: install dependencies
        run: pip install -r dev-deps/lint.txt
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --verbose
