name: pre-commit
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: update wheel, setuptools, and pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - name: install pylint
        run: python -m pip install -r requirements/pylint.txt
      - uses: pre-commit/action@v2.0.3
