# https://github.com/marketplace/actions/github-actions-version-updater

name: Update GitHub Actions

"on":
  workflow_dispatch:
  schedule:
    # First day of each month at noon
    - cron: "0 12 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.ACTIONS_VERSION_UPDATER_TOKEN }}
      # https://github.com/saadmk11/github-actions-version-updater/issues/49#issuecomment-1356182123
      # - uses: saadmk11/github-actions-version-updater@v0.7.1
      - uses: saadmk11/github-actions-version-updater@safe-dir
        with:
          token: ${{ secrets.ACTIONS_VERSION_UPDATER_TOKEN }}
          update_version_with: release-commit-sha
